### ISSUE TITLE
我已阅读并同意iconfont的法律声明  点击无效

### ISSUE THREAD

**Issue by newfun1994** [thx/iconfont-plus#174]
登录后点击 我已阅读并同意iconfont的法律声明   无效
控制台异常log
`VM2330:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.pe.parseJSON (http://g.alicdn.com/mm/iconfont-plus-bp/0.0.22/app/libs/jquery-1.12.1.js:3:19511)
    at Object.complete (http://g.alicdn.com/mm/iconfont-plus-bp/0.0.22/app/models/service.js:1:903)
    at l (http://g.alicdn.com/mm/iconfont-plus-bp/0.0.22/app/libs/jquery-1.12.1.js:2:9338)
    at Object.fireWith (http://g.alicdn.com/mm/iconfont-plus-bp/0.0.22/app/libs/jquery-1.12.1.js:2:10107)
    at r (http://g.alicdn.com/mm/iconfont-plus-bp/0.0.22/app/libs/jquery-1.12.1.js:3:21659)
    at XMLHttpRequest.n (http://g.alicdn.com/mm/iconfont-plus-bp/0.0.22/app/libs/jquery-1.12.1.js:3:27804)
    pe.parseJSON @ jquery-1.12.1.js:3
    complete @ service.js:1
    l @ jquery-1.12.1.js:2
    fireWith @ jquery-1.12.1.js:2
    r @ jquery-1.12.1.js:3
    n @ jquery-1.12.1.js:3`

**Comment by purplebamboo** [comment]
亲  是哪个浏览器下？

**Comment by newfun1994** [comment]
chrome 今天，好了 谢谢
