### ISSUE TITLE
在react中import iconfont.js 报 RangeError

### ISSUE THREAD

**Issue by lulei90** [thx/iconfont-plus#364]
webpack打包过程中 报错
想知道 如何在react项目中使用iconfont.js?

ERROR in ./src/font/iconfont.js
Module build failed: RangeError: D:/works/react-m4.0/src/font/iconfont.js: Maximum call stack size exceeded
    at Function.get (D:\works\react-m4.0\node_modules\babel-traverse\lib\path\index.js:88:29)
    at TraversalContext.create (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:68:27)
    at TraversalContext.visitSingle (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:108:36)
    at TraversalContext.visit (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (D:\works\react-m4.0\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (D:\works\react-m4.0\node_modules\babel-traverse\lib\path\context.js:115:19)
    at TraversalContext.visitQueue (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (D:\works\react-m4.0\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (D:\works\react-m4.0\node_modules\babel-traverse\lib\path\context.js:115:19)
    at TraversalContext.visitQueue (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (D:\works\react-m4.0\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (D:\works\react-m4.0\node_modules\babel-traverse\lib\path\context.js:115:19)
    at TraversalContext.visitQueue (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (D:\works\react-m4.0\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (D:\works\react-m4.0\node_modules\babel-traverse\lib\path\context.js:115:19)
    at TraversalContext.visitQueue (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (D:\works\react-m4.0\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (D:\works\react-m4.0\node_modules\babel-traverse\lib\path\context.js:115:19)
    at TraversalContext.visitQueue (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (D:\works\react-m4.0\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (D:\works\react-m4.0\node_modules\babel-traverse\lib\index.js:114:17)
 @ ./src/index.js 39:0-29

**Comment by lulei90** [comment]
已经解决了 
在webpack 中配置js loader处理的时候 排除掉iconfont.js 就好了
